version: "3"
services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASS}

  cwfparser:
    image: sintax/cwfparser
    environment:
      - NEO4J_HOST
      - NEO4J_HTTP_PORT
      - NEO4J_USER
      - NEO4J_PASS
    command: ["./wait-for-it.sh", "${NEO4J_HOST}:${NEO4J_HTTP_PORT}", "--", "python", "app.py"]

  cwfviz:
    build: .
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      #- DEBUG=express:* # For debugging
      - NEO4J_HOST
      - NEO4J_HTTP_PORT
      - NEO4J_USER
      - NEO4J_PASS
    volumes:
      - ./app:/home/node/app
    ports:
      - "8080:8080"
    expose:
      - "8080"
    command: ["./wait-for-it.sh", "${NEO4J_HOST}:${NEO4J_HTTP_PORT}", "--", "npm", "start"]